import { type NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import CtaForm from "../components/CtaForm";
import PrayerTimes from "../components/PrayerTimes";
import News from "../components/News";
import Events from "../components/Events";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Navbar />
        <Hero />
        <News />
        <PrayerTimes />
        <Events />
        <CtaForm />
        <Footer/>
      </main>
    </>
  );
};

export default Home;
