/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    execs: ExecAuthOperations;
  };
  blocks: {};
  collections: {
    execs: Exec;
    link: Link;
    Instagram: Instagram;
    resources: Resource;
    media: Media;
    members: Member;
    Socials: Social;
    Products: Product;
    Posts: Post;
    categories: Category;
    tags: Tag;
    Sizes: Size;
    recording: Recording;
    WeeklyEvents: WeeklyEvent;
    'jummah-timings': JummahTiming;
    'prayer-rooms': PrayerRoom;
    services: Service;
    'email-collection': EmailCollection;
    'distribution-list': DistributionList;
    individuals: Individual;
    'iia-services': IiaService;
    faq: Faq;
    'halal-directory': HalalDirectory;
    RoommatePosts: RoommatePost;
    comments: Comment;
    events: Event;
    GeneralUser: GeneralUser;
    'daily-reminders': DailyReminder;
    'halal-grocery-stores': HalalGroceryStore;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    execs: ExecsSelect<false> | ExecsSelect<true>;
    link: LinkSelect<false> | LinkSelect<true>;
    Instagram: InstagramSelect<false> | InstagramSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    Socials: SocialsSelect<false> | SocialsSelect<true>;
    Products: ProductsSelect<false> | ProductsSelect<true>;
    Posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    Sizes: SizesSelect<false> | SizesSelect<true>;
    recording: RecordingSelect<false> | RecordingSelect<true>;
    WeeklyEvents: WeeklyEventsSelect<false> | WeeklyEventsSelect<true>;
    'jummah-timings': JummahTimingsSelect<false> | JummahTimingsSelect<true>;
    'prayer-rooms': PrayerRoomsSelect<false> | PrayerRoomsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'email-collection': EmailCollectionSelect<false> | EmailCollectionSelect<true>;
    'distribution-list': DistributionListSelect<false> | DistributionListSelect<true>;
    individuals: IndividualsSelect<false> | IndividualsSelect<true>;
    'iia-services': IiaServicesSelect<false> | IiaServicesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'halal-directory': HalalDirectorySelect<false> | HalalDirectorySelect<true>;
    RoommatePosts: RoommatePostsSelect<false> | RoommatePostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    GeneralUser: GeneralUserSelect<false> | GeneralUserSelect<true>;
    'daily-reminders': DailyRemindersSelect<false> | DailyRemindersSelect<true>;
    'halal-grocery-stores': HalalGroceryStoresSelect<false> | HalalGroceryStoresSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    nav: Nav;
    footer: Footer;
    'prayer-timings': PrayerTiming;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'prayer-timings': PrayerTimingsSelect<false> | PrayerTimingsSelect<true>;
  };
  locale: null;
  user: Exec & {
    collection: 'execs';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ExecAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execs".
 */
export interface Exec {
  id: number;
  name?: string | null;
  department?:
    | (
        | 'marketing'
        | 'events_brothers'
        | 'events_sisters'
        | 'religious_affairs_brothers'
        | 'religious_affairs_sisters'
        | 'finance'
        | 'community_engagement'
        | 'operations'
        | 'technology'
      )
    | null;
  position?: ('vice_president' | 'head_director' | 'director') | null;
  'student id'?: number | null;
  major?: string | null;
  year?: number | null;
  'phone number'?: number | null;
  'mylaurier email'?: string | null;
  city?: string | null;
  roles?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link".
 */
export interface Link {
  id: number;
  title?: string | null;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Instagram".
 */
export interface Instagram {
  id: number;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  category: '1' | '2' | '3' | '4';
  link: (number | Link)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  mylaurierEmail: string;
  studentId?: string | null;
  newsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Socials".
 */
export interface Social {
  id: number;
  title: string;
  link: number | Link;
  icon: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Products".
 */
export interface Product {
  id: number;
  name: string;
  price: number;
  desc: string;
  image: (number | Media)[];
  tags: number | Tag;
  sizes?: (number | null) | Size;
  quantity?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title?: string | null;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Sizes".
 */
export interface Size {
  id: number;
  size: 'Small' | 'Medium' | 'Large';
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  description?: string | null;
  header_image?: (number | Media)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories: number | Category;
  tags?: (number | Tag)[] | null;
  authors?: (number | Exec)[] | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording".
 */
export interface Recording {
  id: number;
  title?: string | null;
  url: string;
  category: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WeeklyEvents".
 */
export interface WeeklyEvent {
  id: number;
  name: string;
  day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
  timeStart: string;
  timeEnd: string;
  location: string;
  caption: string;
  image: (number | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jummah-timings".
 */
export interface JummahTiming {
  id: number;
  building: string;
  room_number?: number | null;
  timing: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-rooms".
 */
export interface PrayerRoom {
  id: number;
  building: string;
  description: string;
  room_number: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  link: number | Link;
  updatedAt: string;
  createdAt: string;
}
/**
 * Collection of emails for marketing purposes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-collection".
 */
export interface EmailCollection {
  id: number;
  title?: string | null;
  subject?: string | null;
  attachments?: (number | Media)[] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  distributionList?: (number | null) | DistributionList;
  Send?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distribution-list".
 */
export interface DistributionList {
  id: number;
  listName: string;
  emails: (number | Individual)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "individuals".
 */
export interface Individual {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iia-services".
 */
export interface IiaService {
  id: number;
  name: string;
  caption: string;
  image: (number | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  Question: string;
  Answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "halal-directory".
 */
export interface HalalDirectory {
  id: number;
  name: string;
  category:
    | 'chinese'
    | 'persian'
    | 'shawarma'
    | 'burgers'
    | 'bangladeshi'
    | 'chinese-indo-fusion'
    | 'pakistani-food'
    | 'chicken-and-waffles'
    | 'kabob'
    | 'uyghur'
    | 'chicken'
    | 'indian-fusion-food'
    | 'pizza';
  slaughtered?: ('hand' | 'machine' | 'both' | 'n/a') | null;
  shortDescription: string;
  location: string;
  googleMapsLink: string;
  website?: string | null;
  image?: (number | null) | Media;
  is_on_campus: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoommatePosts".
 */
export interface RoommatePost {
  id: number;
  userId: number | GeneralUser;
  author?: string | null;
  email?: string | null;
  contactEmail: boolean;
  title: string;
  address: string;
  description: string;
  rent: number;
  deposit?: number | null;
  gender: '1' | '2';
  propertyType: '1' | '2' | '3' | '4';
  furnishingType: '1' | '2' | '3';
  utilities?: ('1' | '2' | '3' | '4' | '5' | '6')[] | null;
  amenities?: ('1' | '2' | '3' | '4' | '5')[] | null;
  images: string[];
  availableDate: string;
  facebook?: string | null;
  phoneNumber?: string | null;
  instagram?: string | null;
  whatsapp?: string | null;
  status?: ('pending' | 'approved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralUser".
 */
export interface GeneralUser {
  id: number;
  clerkId: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  category?: ('student' | 'landlord' | 'parent' | 'business' | 'alumni') | null;
  laurierEmail?: string | null;
  studentId?: string | null;
  year?: string | null;
  program?: string | null;
  newsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  author?: string | null;
  comment?: string | null;
  postId: number | RoommatePost;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  date?: string | null;
  time?: string | null;
  location?: string | null;
  description: string;
  image?: (number | null) | Media;
  link?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-reminders".
 */
export interface DailyReminder {
  id: number;
  reference: string;
  arabic: string;
  english: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "halal-grocery-stores".
 */
export interface HalalGroceryStore {
  id: number;
  name: string;
  category:
    | 'full-grocery'
    | 'halal-meat'
    | 'international'
    | 'specialty'
    | 'convenience'
    | 'bakery'
    | 'spice'
    | 'frozen';
  halalCertification: 'certified' | 'muslim-owned' | 'halal-friendly' | 'not-specified';
  shortDescription: string;
  location: string;
  googleMapsLink: string;
  website?: string | null;
  phone?: string | null;
  hours?: string | null;
  specialties?:
    | {
        specialty: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  is_on_campus: boolean;
  priceRange?: ('1' | '2' | '3' | '4') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label: string;
            width?: number | null;
            isMultipleChoice?: boolean | null;
            checkboxes: {
              label?: string | null;
              limit?: number | null;
              value?: boolean | null;
              id?: string | null;
            }[];
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            basePrice?: number | null;
            priceConditions?:
              | {
                  fieldToUse?: string | null;
                  condition?: ('hasValue' | 'equals' | 'notEquals') | null;
                  valueForCondition?: string | null;
                  operator?: ('add' | 'subtract' | 'multiply' | 'divide') | null;
                  valueType?: ('static' | 'valueOfField') | null;
                  valueForOperator?: string | null;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'payment';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            default_value?: string | null;
            options?:
              | {
                  label?: string | null;
                  value?: string | null;
                  limit?: number | null;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            first_name?: string | null;
            first_name_placeholder?: string | null;
            last_name?: string | null;
            last_name_placeholder?: string | null;
            email?: string | null;
            email_placeholder?: string | null;
            studentID?: string | null;
            studentID_placeholder?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  submissionLimit?: number | null;
  releaseDate?: string | null;
  closeDate?: string | null;
  slug?: string | null;
  webhook?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payment?: {
    amount?: number | null;
    status?: ('pending' | 'paid' | 'cancelled' | 'refunded') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'execs';
        value: number | Exec;
      } | null)
    | ({
        relationTo: 'link';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'Instagram';
        value: number | Instagram;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'Socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'Products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'Posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'Sizes';
        value: number | Size;
      } | null)
    | ({
        relationTo: 'recording';
        value: number | Recording;
      } | null)
    | ({
        relationTo: 'WeeklyEvents';
        value: number | WeeklyEvent;
      } | null)
    | ({
        relationTo: 'jummah-timings';
        value: number | JummahTiming;
      } | null)
    | ({
        relationTo: 'prayer-rooms';
        value: number | PrayerRoom;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'email-collection';
        value: number | EmailCollection;
      } | null)
    | ({
        relationTo: 'distribution-list';
        value: number | DistributionList;
      } | null)
    | ({
        relationTo: 'individuals';
        value: number | Individual;
      } | null)
    | ({
        relationTo: 'iia-services';
        value: number | IiaService;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'halal-directory';
        value: number | HalalDirectory;
      } | null)
    | ({
        relationTo: 'RoommatePosts';
        value: number | RoommatePost;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'GeneralUser';
        value: number | GeneralUser;
      } | null)
    | ({
        relationTo: 'daily-reminders';
        value: number | DailyReminder;
      } | null)
    | ({
        relationTo: 'halal-grocery-stores';
        value: number | HalalGroceryStore;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'execs';
    value: number | Exec;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'execs';
    value: number | Exec;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execs_select".
 */
export interface ExecsSelect<T extends boolean = true> {
  name?: T;
  department?: T;
  position?: T;
  'student id'?: T;
  major?: T;
  year?: T;
  'phone number'?: T;
  'mylaurier email'?: T;
  city?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_select".
 */
export interface LinkSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Instagram_select".
 */
export interface InstagramSelect<T extends boolean = true> {
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  mylaurierEmail?: T;
  studentId?: T;
  newsletter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  title?: T;
  link?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  desc?: T;
  image?: T;
  tags?: T;
  sizes?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  header_image?: T;
  content?: T;
  categories?: T;
  tags?: T;
  authors?: T;
  status?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  size?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording_select".
 */
export interface RecordingSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WeeklyEvents_select".
 */
export interface WeeklyEventsSelect<T extends boolean = true> {
  name?: T;
  day?: T;
  timeStart?: T;
  timeEnd?: T;
  location?: T;
  caption?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jummah-timings_select".
 */
export interface JummahTimingsSelect<T extends boolean = true> {
  building?: T;
  room_number?: T;
  timing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-rooms_select".
 */
export interface PrayerRoomsSelect<T extends boolean = true> {
  building?: T;
  description?: T;
  room_number?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-collection_select".
 */
export interface EmailCollectionSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  attachments?: T;
  content?: T;
  content_html?: T;
  status?: T;
  publishedAt?: T;
  distributionList?: T;
  Send?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distribution-list_select".
 */
export interface DistributionListSelect<T extends boolean = true> {
  listName?: T;
  emails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "individuals_select".
 */
export interface IndividualsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iia-services_select".
 */
export interface IiaServicesSelect<T extends boolean = true> {
  name?: T;
  caption?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  Question?: T;
  Answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "halal-directory_select".
 */
export interface HalalDirectorySelect<T extends boolean = true> {
  name?: T;
  category?: T;
  slaughtered?: T;
  shortDescription?: T;
  location?: T;
  googleMapsLink?: T;
  website?: T;
  image?: T;
  is_on_campus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoommatePosts_select".
 */
export interface RoommatePostsSelect<T extends boolean = true> {
  userId?: T;
  author?: T;
  email?: T;
  contactEmail?: T;
  title?: T;
  address?: T;
  description?: T;
  rent?: T;
  deposit?: T;
  gender?: T;
  propertyType?: T;
  furnishingType?: T;
  utilities?: T;
  amenities?: T;
  images?: T;
  availableDate?: T;
  facebook?: T;
  phoneNumber?: T;
  instagram?: T;
  whatsapp?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  comment?: T;
  postId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  time?: T;
  location?: T;
  description?: T;
  image?: T;
  link?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralUser_select".
 */
export interface GeneralUserSelect<T extends boolean = true> {
  clerkId?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  category?: T;
  laurierEmail?: T;
  studentId?: T;
  year?: T;
  program?: T;
  newsletter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-reminders_select".
 */
export interface DailyRemindersSelect<T extends boolean = true> {
  reference?: T;
  arabic?: T;
  english?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "halal-grocery-stores_select".
 */
export interface HalalGroceryStoresSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  halalCertification?: T;
  shortDescription?: T;
  location?: T;
  googleMapsLink?: T;
  website?: T;
  phone?: T;
  hours?: T;
  specialties?:
    | T
    | {
        specialty?: T;
        id?: T;
      };
  image?: T;
  is_on_campus?: T;
  priceRange?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              isMultipleChoice?: T;
              checkboxes?:
                | T
                | {
                    label?: T;
                    limit?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        payment?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              basePrice?: T;
              priceConditions?:
                | T
                | {
                    fieldToUse?: T;
                    condition?: T;
                    valueForCondition?: T;
                    operator?: T;
                    valueType?: T;
                    valueForOperator?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              default_value?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    limit?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              first_name?: T;
              first_name_placeholder?: T;
              last_name?: T;
              last_name_placeholder?: T;
              email?: T;
              email_placeholder?: T;
              studentID?: T;
              studentID_placeholder?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  submissionLimit?: T;
  releaseDate?: T;
  closeDate?: T;
  slug?: T;
  webhook?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?: T;
  payment?:
    | T
    | {
        amount?: T;
        status?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  items: {
    label?: string | null;
    links: {
      title?: string | null;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  items: {
    label?: string | null;
    links: {
      title?: string | null;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-timings".
 */
export interface PrayerTiming {
  id: number;
  month: {
    month:
      | 'January'
      | 'February'
      | 'March'
      | 'April'
      | 'May'
      | 'June'
      | 'July'
      | 'August'
      | 'September'
      | 'October'
      | 'November'
      | 'December';
    days: {
      day: number;
      fajr: string;
      fajr_iqamah?: string | null;
      sunrise: string;
      dhuhr: string;
      dhuhr_iqamah_1: string;
      dhuhr_iqamah_2?: string | null;
      asr: string;
      asr_iqamah_1: string;
      maghrib: string;
      maghrib_iqamah: string;
      isha: string;
      isha_iqamah?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              title?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              title?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-timings_select".
 */
export interface PrayerTimingsSelect<T extends boolean = true> {
  month?:
    | T
    | {
        month?: T;
        days?:
          | T
          | {
              day?: T;
              fajr?: T;
              fajr_iqamah?: T;
              sunrise?: T;
              dhuhr?: T;
              dhuhr_iqamah_1?: T;
              dhuhr_iqamah_2?: T;
              asr?: T;
              asr_iqamah_1?: T;
              maghrib?: T;
              maghrib_iqamah?: T;
              isha?: T;
              isha_iqamah?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}