import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../../styles/globals.css"
import { Providers } from '@/redux/Provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en ">
      <Providers>
      <body className={inter.className} >{children}</body>
      </Providers>
    </html>
  )
}
