import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import { Providers } from "@/redux/Provider";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/Global/Navbar";
import Footer from "@/components/Global/Footer";
import { getNavbarData, getFooterData, fetchSocialLinks } from "@/Utils/api";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navbarData = await getNavbarData();
  const socialLinks = await fetchSocialLinks();
  const footerData = await getFooterData();
  return (
    <html lang="en">
      <body >
        <Providers>
          <Navbar navbarData={navbarData} />
          {children}
          <Footer footerGroups={footerData} socialLinks={socialLinks} />
        </Providers>
      </body>
    </html>
  );
}
