/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vR3Lsw054Hy
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/UI/card"
import { JSX, SVGProps } from "react"

export function VideoCards() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center justify-between h-16 px-4 border-b md:px-6">
        <h1 className="text-2xl font-bold">Category Name</h1>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-gray-100/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 dark:bg-gray-800/40">
        <div className="grid gap-6 md:grid-cols-3 lg:grid-cols-4 max-w-6xl w-full mx-auto">
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <PlayIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Video 1</CardTitle>
                <CardDescription>Video 1 description</CardDescription>
                <div className="flex gap-2">
                  <span className="inline-block bg-green-200 text-green-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 1
                  </span>
                  <span className="inline-block bg-blue-200 text-blue-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 2
                  </span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex justify-center items-center">
              <img
                alt="Video thumbnail"
                className="aspect-square object-cover"
                height={200}
                src="/placeholder.svg"
                width={200}
              />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <PlayIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Video 2</CardTitle>
                <CardDescription>Video 2 description</CardDescription>
                <div className="flex gap-2">
                  <span className="inline-block bg-red-200 text-red-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 3
                  </span>
                  <span className="inline-block bg-purple-200 text-purple-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 4
                  </span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex justify-center items-center">
              <img
                alt="Video thumbnail"
                className="aspect-square object-cover"
                height={200}
                src="/placeholder.svg"
                width={200}
              />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <PlayIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Video 3</CardTitle>
                <CardDescription>Video 3 description</CardDescription>
                <div className="flex gap-2">
                  <span className="inline-block bg-yellow-200 text-yellow-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 5
                  </span>
                  <span className="inline-block bg-teal-200 text-teal-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 6
                  </span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex justify-center items-center">
              <img
                alt="Video thumbnail"
                className="aspect-square object-cover"
                height={200}
                src="/placeholder.svg"
                width={200}
              />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <PlayIcon className="w-8 h-8" />
              <div className="grid gap-1">
                <CardTitle>Video 4</CardTitle>
                <CardDescription>Video 4 description</CardDescription>
                <div className="flex gap-2">
                  <span className="inline-block bg-pink-200 text-pink-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 7
                  </span>
                  <span className="inline-block bg-gray-200 text-gray-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                    Tag 8
                  </span>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex justify-center items-center">
              <img
                alt="Video thumbnail"
                className="aspect-square object-cover"
                height={200}
                src="/placeholder.svg"
                width={200}
              />
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function PlayIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  )
}
